version: "3.8"

services:
  minio:
    image: bitnami/minio:latest

    container_name: minio
    restart: unless-stopped

    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9900:9000"
      - "9901:9001"
    volumes:
      - minio-data:/data

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  postgres:
    image: postgres:16.2-alpine
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: app
    ports:
      - "8020:5432"
    volumes:
      - /var/docker-db-lab/:/var/lib/postgresql/data


  rabbitmq:
    image: rabbitmq:3.13-alpine
    container_name: rabbitmq
    hostname: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq123
      RABBITMQ_MANAGEMENT_ALLOW_WEB_ACCESS: true
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq

volumes:
  minio-data:
    driver: local