server:
  port: ${GATEWAY_PORT:9443}

springdoc:
  swagger-ui:
    configUrl: "/swagger-config.json"

spring:
  application:
    name: gateway-app
  cloud:
    gateway:
      routes:
        - id: user-app
          uri: http://localhost:9444
          predicates:
            - Path=/api/user/**
            - Path=/api/admin/**
        - id: forum-app
          uri: http://localhost:9445
          predicates:
            - Path=/api/forum/**
        - id: file-app
          uri: http://localhost:9446
          predicates:
            - Path=/api/file/**
        - id: notification-app
          uri: http://localhost:9447
          predicates:
            - Path=/api/notification/**