server:
  port: ${GATEWAY_PORT:9443}

spring:
  application:
    name: gateway-app
  cloud:
    gateway:
      routes:
        - id: user-app
          uri: http://localhost:9444
          predicates:
            - Path=/api/user/**
        - id: forum-app
          uri: http://localhost:9445
          predicates:
            - Path=/api/forum/**
        - id: file-app
          uri: http://localhost:9446
          predicates:
            - Path=/api/file/**