server:
  port: ${USER_APP_PORT:9444}

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/messenger}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:123}
    driver-class-name: org.postgresql.Driver
  flyway:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/messenger}
    user: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:123}
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL_AUTO:validate}
    show-sql: true

jwt:
  secret: ${JWT_SECRET:secret}
  expiration-time: ${JWT_EXPIRATION_TIME:86400000}

logging:
  level:
    org:
      springframework:
        security: ${LOGGING_LEVEL_SPRING_SECURITY:TRACE}

