server:
  port: ${USER_APP_PORT:9444}

spring:
  datasource:
    url: ${USER_DATABASE_URL:jdbc:postgresql://localhost:5432/user_db}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:123}
    driver-class-name: org.postgresql.Driver
  flyway:
    url: ${USER_DATABASE_URL:jdbc:postgresql://localhost:5432/user_db}
    user: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:123}
    baseline-on-migrate: true
    locations: classpath:db/migration/user
  jpa:
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL_AUTO:validate}
    show-sql: true
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS:localhost:9092}

topic:
  notification:
    name:
      ${NOTIFICATION_TOPIC_NAME:notification_topic}
    group-id: 1
  emailing:
    name:
      ${EMAILING_TOPIC_NAME:emailing_topic}
    group-id: 1

logging:
  level:
    org:
      springframework:
        security: ${LOGGING_LEVEL_SPRING_SECURITY:TRACE}

