server:
  port: 8085

jwt:
  secret: "fda32faa4f2c8d3b7a1e6f45fad4sf8a0b434df7d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d9"
  expiration-time: 86400000
  token-prefix: "Bearer "

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/messenger
    username: postgres
    password: 123
  security:
    user:
      name: admin
      password: admin
logging:
  level:
    org:
      springframework:
        security: DEBUG