server:
  port: ${FORUM_APP_PORT:9445}

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/messenger}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:123}
    driver-class-name: org.postgresql.Driver
  flyway:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/messenger}
    user: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:123}
    baseline-on-migrate: true
  jpa:
    hibernate:
        ddl-auto: validate
    show-sql: true

logging:
  level:
    org:
      springframework:
        security: TRACE