server:
  port: ${FORUM_APP_PORT}

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    url: ${DATABASE_URL}
    user: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    baseline-on-migrate: true
  jpa:
    hibernate:
        ddl-auto: validate
    show-sql: true

logging:
  level:
    org:
      springframework:
        security: ${LOGGING_LEVEL_SPRING_FRAMEWORK_SECURITY}