server:
  port: ${FORUM_APP_PORT:9445}

spring:
  datasource:
    url: ${FORUM_DATABASE_URL:jdbc:postgresql://localhost:5432/forum_db}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:123}
    driver-class-name: org.postgresql.Driver

  flyway:
    url: ${FORUM_DATABASE_URL:jdbc:postgresql://localhost:5432/forum_db}
    user: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:123}
    baseline-on-migrate: true
    locations: classpath:db/migration/forum

  jpa:
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL_AUTO:validate}
    show-sql: true
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS:localhost:9092}
logging:
  level:
    org:
      springframework:
        security: ${LOGGING_LEVEL_SPRING_SECURITY:TRACE}

topic:
  notification:
    name:
      ${NOTIFICATION_TOPIC_NAME:notification_topic}
    group-id: 1

