server:
  port: ${NOTIFICATION_PORT:9447}

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq
    password: rabbitmq123
  datasource:
    url: ${NOTIFICATION_DATABASE_URL:jdbc:postgresql://localhost:5432/notification_db}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:123}
    driver-class-name: org.postgresql.Driver
  flyway:
    url: ${NOTIFICATION_DATABASE_URL:jdbc:postgresql://localhost:5432/notification_db}
    user: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:123}
    baseline-on-migrate: true
    locations: classpath:db/migration/notification
  jpa:
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL_AUTO:validate}
    show-sql: true

rabbitmq:
  queue:
    topic:
      topic_queue
  exchange:
    name: exchange
  routing_key:
    routing_key
  user:
    name:
      rabbitmq
    password:
      rabbitmq123

logging:
  level:
    org:
      springframework:
        security: ${LOGGING_LEVEL_SPRING_SECURITY:TRACE}