server:
  port: ${NOTIFICATION_PORT:9447}

spring:
  datasource:
    url: ${NOTIFICATION_DATABASE_URL:jdbc:postgresql://localhost:5432/notification_db}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:123}
    driver-class-name: org.postgresql.Driver

  flyway:
    url: ${NOTIFICATION_DATABASE_URL:jdbc:postgresql://localhost:5432/notification_db}
    user: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:123}
    baseline-on-migrate: true
    locations: classpath:db/migration/notification

  jpa:
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL_AUTO:validate}
    show-sql: true

  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: 1

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        debug: ${MAIL_DEBUG}
        transport:
          protocol: smtp
        smtp:
          auth: ${MAIL_AUTH}
          starttls:
            enable: ${MAIL_STARTTLS}

topic:
  notification:
    name:
      ${NOTIFICATION_TOPIC_NAME:notification_topic}
    group-id: 1
  emailing:
    name:
      ${EMAILING_TOPIC_NAME:emailing_topic}
    group-id: 1

logging:
  level:
    org:
      springframework:
        security: ${LOGGING_LEVEL_SPRING_SECURITY:TRACE}